"""&MESH text, merged output file and report."""

import re

import numpy as np

from .parse import parse_namelists


def fmt(x):
    """Coordinate text: 6 decimals, trailing zeros stripped."""
    s = f"{x:.6f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def _xb(grid, lo, hi):
    return ",".join(fmt(grid.coord(i, a)) for a in range(3)
                    for i in (lo[a], hi[a]))


def mesh_lines(grid, layout, mpi=None):
    """List of &MESH lines, one per retained block."""
    starts = layout.block_starts()
    b = np.array(layout.b)
    n = len(starts)
    # sort so the dominant axis (most blocks) is the slowest key
    order = np.argsort(layout.blocks.shape)
    keys = tuple(starts[:, a] for a in order)        # last key = primary
    starts = starts[np.lexsort(keys)]
    width = max(4, len(str(n)))
    lines = []
    for m, s in enumerate(starts):
        mp = f", MPI_PROCESS={m * mpi // n}" if mpi else ""
        lines.append(f"&MESH ID='M_{m + 1:0{width}d}', "
                     f"IJK={b[0]},{b[1]},{b[2]}, XB={_xb(grid, s, s + b)}{mp} /")
    return lines


def build_snippet(grid, layout, mpi=None):
    return "\n".join(["! --- generated by fds_mesher ---"]
                     + mesh_lines(grid, layout, mpi)) + "\n"


def merge_into_text(model, snippet):
    """Original text with &MESH commented out and the snippet inserted."""
    lines = model.text.splitlines(keepends=True)
    meshes = [nl for nl in model.namelists if nl.name == "MESH"]
    for nl in meshes:
        for ln in range(nl.line, nl.line_end + 1):
            lines[ln - 1] = "!MESH-AUTO " + lines[ln - 1]
    if meshes:
        at = meshes[0].line - 1
    else:
        heads = [nl for nl in model.namelists if nl.name == "HEAD"]
        at = heads[0].line_end if heads else 0
    if at > 0 and not lines[at - 1].endswith("\n"):
        lines[at - 1] += "\n"
    lines.insert(at, snippet)
    return "".join(lines)


def format_report(res, dx):
    """Human-readable report (see plan section 3.6)."""
    g, lay, rr = res.grid, res.layout, res.reach
    size = g.upper() - g.origin
    full = g.n_voxels
    total = lay.n_blocks * lay.cells_per_block
    ext = [n * dx for n in lay.b]
    off = tuple(-s for s in lay.start)
    out = [
        f"dx: {dx:g} m   domain: {size[0]:g} x {size[1]:g} x {size[2]:g} m   "
        f"bounds from: {g.bounds_source}",
        f"voxels: {full / 1e6:.2f} M   solid: {rr.n_solid / 1e6:.2f} M   "
        f"reachable air: {rr.n_reachable / 1e6:.2f} M   "
        f"unreachable air: {rr.n_unreachable / 1e6:.2f} M",
        f"block: {lay.b[0]} x {lay.b[1]} x {lay.b[2]} cells "
        f"({ext[0]:g} x {ext[1]:g} x {ext[2]:g} m)   offset: {off}",
        f"meshes: {lay.n_blocks}   total cells: {total / 1e6:.2f} M   "
        f"cells/mesh: {lay.cells_per_block}",
        f"efficiency (reachable/meshed): {100 * rr.n_reachable / total:.0f} %   "
        f"removed vs. full box: {max(0, 100 * (1 - total / full)):.0f} %",
        f"est. memory: ~{total * 1e3 / 1e9:.1f} GB (1 kB/cell)",
    ]
    out += [f"WARNING: {w}" for w in res.warnings]
    out += [f"VALIDATION FAILED: {e}" for e in res.errors]
    return "\n".join(out)
