"""&MESH text, merged output file and report."""

import re

import numpy as np

from .parse import parse_namelists


def fmt(x):
    """Coordinate text: 6 decimals, trailing zeros stripped."""
    s = f"{x:.6f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def _xb(grid, lo, hi):
    return ",".join(fmt(grid.coord(i, a)) for a in range(3)
                    for i in (lo[a], hi[a]))


def mesh_lines(grid, layout, mpi=None):
    """List of &MESH lines, one per retained block."""
    lo, hi = layout.block_boxes()
    n = len(lo)
    # sort so the dominant axis (most blocks) is the slowest key
    order = np.argsort(layout.blocks.shape)
    keys = tuple(lo[:, a] for a in order)            # last key = primary
    srt = np.lexsort(keys)
    lo, hi = lo[srt], hi[srt]
    width = max(4, len(str(n)))
    lines = []
    for m, (l, h) in enumerate(zip(lo, hi)):
        ijk = h - l
        mp = f", MPI_PROCESS={m * mpi // n}" if mpi else ""
        lines.append(f"&MESH ID='M_{m + 1:0{width}d}', "
                     f"IJK={ijk[0]},{ijk[1]},{ijk[2]}, XB={_xb(grid, l, h)}{mp} /")
    return lines


def overhang_boxes(grid, layout):
    """Index boxes (lo, hi) covering the retained blocks outside the grid.

    Each block minus the grid box is cut into at most six slabs; slabs that
    touch along an axis with identical other extents are merged.
    """
    n = np.array(grid.shape)
    boxes = []
    for lo, hi in zip(*layout.block_boxes()):
        lo, hi = lo.copy(), hi.copy()
        if (lo >= 0).all() and (hi <= n).all():
            continue
        for a in range(3):
            if lo[a] < 0:
                l2, h2 = lo.copy(), hi.copy()
                h2[a] = min(0, hi[a])
                boxes.append((l2, h2))
            if hi[a] > n[a]:
                l2, h2 = lo.copy(), hi.copy()
                l2[a] = max(n[a], lo[a])
                boxes.append((l2, h2))
            lo[a], hi[a] = max(lo[a], 0), min(hi[a], n[a])
    boxes = {tuple(int(v) for a in range(3) for v in (l[a], h[a]))
             for l, h in boxes}
    changed = True
    while changed:
        changed = False
        for a in range(3):
            groups = {}
            for bx in boxes:
                key = tuple(v for k, v in enumerate(bx) if k // 2 != a)
                groups.setdefault(key, []).append((bx[2 * a], bx[2 * a + 1]))
            boxes = set()
            for key, iv in groups.items():
                iv.sort()
                runs = [list(iv[0])]
                for lo_, hi_ in iv[1:]:
                    if lo_ <= runs[-1][1]:
                        runs[-1][1] = max(runs[-1][1], hi_)
                        changed = True
                    else:
                        runs.append([lo_, hi_])
                for lo_, hi_ in runs:
                    bx = list(key)
                    bx[2 * a:2 * a] = [lo_, hi_]
                    boxes.add(tuple(bx))
    return [((b[0], b[2], b[4]), (b[1], b[3], b[5])) for b in sorted(boxes)]


def build_snippet(grid, layout, mpi=None, fill_overhang=True):
    """&MESH lines plus (optionally) &OBST fillers for overhang cells."""
    lines = ["! --- generated by fds_mesher ---"] + mesh_lines(grid, layout, mpi)
    if fill_overhang:
        fill = overhang_boxes(grid, layout)
        if fill:
            lines.append("! solid fill of mesh cells outside the voxel domain")
        lines += [f"&OBST XB={_xb(grid, l, h)} /" for l, h in fill]
    return "\n".join(lines) + "\n"


def merge_into_text(model, snippet):
    """Original text with &MESH commented out and the snippet inserted."""
    lines = model.text.splitlines(keepends=True)
    meshes = [nl for nl in model.namelists if nl.name == "MESH"]
    for nl in meshes:
        for ln in range(nl.line, nl.line_end + 1):
            lines[ln - 1] = "!MESH-AUTO " + lines[ln - 1]
    if meshes:
        at = meshes[0].line - 1
    else:
        heads = [nl for nl in model.namelists if nl.name == "HEAD"]
        at = heads[0].line_end if heads else 0
    if at > 0 and not lines[at - 1].endswith("\n"):
        lines[at - 1] += "\n"
    lines.insert(at, snippet)
    return "".join(lines)


def _count(n):
    """Cell count as '14.1 M' or a plain integer when small."""
    return f"{n / 1e6:.2f} M" if n >= 1e5 else f"{int(n)}"


def format_report(res, dx):
    """Human-readable report (see plan section 3.6)."""
    g, lay, rr = res.grid, res.layout, res.reach
    size = g.upper() - g.origin
    full = g.n_voxels
    total = lay.total_cells
    ext = [n * dx for n in lay.b]
    off = tuple(-s for s in lay.start)
    lo, hi = lay.block_boxes()
    per = np.prod(hi - lo, axis=1)
    odd = lay.odd_sizes()
    odd_txt = ", ".join(f"{'xyz'[a]}: {'/'.join(map(str, v))}"
                        for a, v in enumerate(odd) if v)
    out = [
        f"dx: {dx:g} m   domain: {size[0]:g} x {size[1]:g} x {size[2]:g} m   "
        f"bounds from: {g.bounds_source}",
        f"voxels: {_count(full)}   solid: {_count(rr.n_solid)}   "
        f"reachable air: {_count(rr.n_reachable)}   "
        f"unreachable air: {_count(rr.n_unreachable)}",
        f"block: {lay.b[0]} x {lay.b[1]} x {lay.b[2]} cells "
        f"({ext[0]:g} x {ext[1]:g} x {ext[2]:g} m)   overhang: {off} cells",
        f"meshes: {lay.n_blocks}   total cells: {_count(total)}   "
        f"cells/mesh: {per.min()}" + (f"-{per.max()}" if per.max() > per.min()
                                      else ""),
        f"efficiency (reachable/meshed): {100 * rr.n_reachable / total:.0f} %   "
        f"removed vs. full box: {max(0, 100 * (1 - total / full)):.0f} %",
        f"layout search: {res.info.get('evaluated', 0)} candidates in "
        f"{res.info.get('seconds', 0):.1f} s",
        f"est. memory: ~{total * 1e3 / 1e9:.1f} GB (1 kB/cell)",
    ]
    if odd_txt:
        out.insert(3, f"end blocks cut/merged to fit flush faces: {odd_txt} cells")
    out += [f"WARNING: {w}" for w in res.warnings]
    out += [f"VALIDATION FAILED: {e}" for e in res.errors]
    return "\n".join(out)
